package in.srnyapathi.bank.persistence.mapper;

import in.srnyapathi.bank.domain.model.Account;
import in.srnyapathi.bank.persistence.entity.AccountEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Mapper interface for converting between {@link Account} domain objects
 * and {@link AccountEntity} persistence entities.
 * <p>
 * This mapper is generated by MapStruct and configured as a Spring component.
 * </p>
 */
@Mapper(componentModel = "spring")
public interface AccountMapper {

    /**
     * Converts an {@link AccountEntity} to an {@link Account} domain object.
     *
     * @param accountEntity the entity to convert
     * @return the corresponding domain object, or null if the input is null
     */
    @Mapping(target = "accountNumber", source = "id")
    Account toDomain(AccountEntity accountEntity);

    /**
     * Converts an {@link Account} domain object to an {@link AccountEntity}.
     *
     * @param account the domain object to convert
     * @return the corresponding entity, or null if the input is null
     */
    @Mapping(target = "isActive", source = "active")
    AccountEntity toEntity(Account account);
}
