package in.srnyapathi.bank.persistence.mapper;

import in.srnyapathi.bank.domain.model.OperationType;
import in.srnyapathi.bank.domain.model.TransactionType;
import in.srnyapathi.bank.persistence.entity.OperationTypeEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;

import java.util.Locale;

/**
 * Mapper interface for converting between {@link OperationType} domain objects
 * and {@link OperationTypeEntity} persistence entities.
 * <p>
 * This mapper is generated by MapStruct and configured as a Spring component.
 * It includes custom mapping logic for transaction type conversions.
 * </p>
 */
@Mapper(componentModel = "spring")
public interface OperationTypeMapper {

    /**
     * Converts an {@link OperationTypeEntity} to an {@link OperationType} domain object.
     *
     * @param entity the entity to convert
     * @return the corresponding domain object, or null if the input is null
     */
    @Mapping(target = "transactionType", source = "type", qualifiedByName = "transactionTypeFromDb")
    @Mapping(target = "operationTypeId", source = "id")
    OperationType toDomain(OperationTypeEntity entity);

    /**
     * Converts an {@link OperationType} domain object to an {@link OperationTypeEntity}.
     *
     * @param domain the domain object to convert
     * @return the corresponding entity, or null if the input is null
     */
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    @Mapping(target = "isActive", ignore = true)
    @Mapping(target = "type", source = "transactionType", qualifiedByName = "transactionTypeToDb")
    @Mapping(target = "id", source = "operationTypeId")
    OperationTypeEntity toEntity(OperationType domain);

    /**
     * Converts a database string value to a {@link TransactionType} enum.
     * <p>
     * Supports both abbreviated (CR, DR) and full names (CREDIT, DEBIT).
     * </p>
     *
     * @param value the database string value
     * @return the corresponding {@link TransactionType}, or null if the input is null
     * @throws IllegalArgumentException if the value is not a supported transaction type
     */
    @Named("transactionTypeFromDb")
    default TransactionType transactionTypeFromDb(String value) {
        if (value == null) {
            return null;
        }
        return switch (value.trim().toUpperCase(Locale.ROOT)) {
            case "CR", "CREDIT" -> TransactionType.CREDIT;
            case "DR", "DEBIT" -> TransactionType.DEBIT;
            default -> throw new IllegalArgumentException("Unsupported transaction type: " + value);
        };
    }

    /**
     * Converts a {@link TransactionType} enum to a database string value.
     *
     * @param value the transaction type enum
     * @return the string representation of the transaction type, or null if the input is null
     */
    @Named("transactionTypeToDb")
    default String transactionTypeToDb(TransactionType value) {
        return value == null ? null : value.name();
    }
}
