package in.srnyapathi.bank.persistence.mapper;

import in.srnyapathi.bank.domain.model.Transaction;
import in.srnyapathi.bank.persistence.entity.TransactionEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Mapper interface for converting between {@link Transaction} domain objects
 * and {@link TransactionEntity} persistence entities.
 * <p>
 * This mapper is generated by MapStruct and configured as a Spring component.
 * It handles nested object mappings for account and operation type relationships.
 * </p>
 */
@Mapper(componentModel = "spring")
public interface TransactionMapper {
    /**
     * Converts a {@link Transaction} domain object to a {@link TransactionEntity}.
     * <p>
     * Maps nested account and operation type objects to their respective IDs.
     * </p>
     *
     * @param domain the domain object to convert
     * @return the corresponding entity, or null if the input is null
     */
    @Mapping(target = "isActive", source = "active")
    @Mapping(target = "accountId", source = "account.id")
    @Mapping(target = "operationTypeId", source = "operationType.operationTypeId")
    TransactionEntity toEntity(Transaction domain);

    /**
     * Converts a {@link TransactionEntity} to a {@link Transaction} domain object.
     * <p>
     * Maps account and operation type IDs to nested object structures.
     * </p>
     *
     * @param domain the entity to convert
     * @return the corresponding domain object, or null if the input is null
     */
    @Mapping(target = "operationType.operationTypeId", source = "operationTypeId")
    @Mapping(target = "account.id", source = "accountId")
    Transaction toDomain(TransactionEntity domain);
}
