-- Seed data for operation_types
-- These are the standard operation types for banking transactions

INSERT INTO operation_types (description, transaction_type, handler, created_at, updated_at, is_active) VALUES
('CASH PURCHASE', 'DEBIT', 'CASH_PURCHASE_TRANSACTION', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE),
('INSTALLMENT PURCHASE', 'DEBIT', 'INSTALLMENT_PURCHASE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE),
('WITHDRAWAL', 'DEBIT', 'WITHDRAWAL', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE),
('PAYMENT', 'CREDIT', 'PAYMENT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE)
ON CONFLICT DO NOTHING;
